# Generated by Django 5.1.7 on 2025-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('game_url', models.URLField()),
                ('freetogame_profile_url', models.URLField()),
                ('release_date', models.DateField()),
                ('short_description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('game_id', models.CharField(max_length=255, unique=True))

            ],
        ),
    ]
