# Generated by Django 5.1.7 on 2025-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
