# Generated by Django 5.1.7 on 2025-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerank', '0005_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
