# Generated by Django 5.1.7 on 2025-05-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerank', '0006_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
